version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR=example

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - ENV_VAR=example
